# Generated by Django 4.2.15 on 2024-12-02 13:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_image",
            field=cloudinary.models.CloudinaryField(
                default="https://res.cloudinary.com/durdklhd9/image/upload/v1733144989/default_avatar_bbz2vo.png",
                max_length=255,
                verbose_name="image",
            ),
        ),
    ]
