# Generated by Django 4.2.15 on 2024-10-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="information",
            field=models.TextField(blank=True, null=True),
        ),
    ]
